name: Build & Publish cyrene-agent

on:
  push:
    branches: [ main ]
    tags:    ['v*']

permissions:
  contents: read      # for checkout
  packages: write     # to push images

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Create default.charater.json file from secret
      #   run: |
      #     echo "${{ secrets.DEFAULT_CHARACTER_JSON }}" > default.charater.json

      - name: Log in to GHCR (pull & push)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_CR_PAT }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .           
          file:    Dockerfile    
          push:    true
          tags: |
            ghcr.io/cyreneai/cyrene-agent:latest
            ghcr.io/cyreneai/cyrene-agent:${{ github.sha }}
